before_script:
  - apk add --update curl && rm -rf /var/cache/apk/*
  - curl -s https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | bash
  - deb http://ftp.fi.debian.org/debian/ buster main contrib non-free
  - deb-src http://ftp.fi.debian.org/debian/ buster main contrib non-free
  - apt-get install icc-profiles

compile_pdf:
  image: tianon/latex
  script:
    - cd prace
    - make
  artifacts:
    paths:
      - prace/prace.pdf
